In [1]:
import numpy as np
import pandas as pd 
from sklearn.feature_selection import mutual_info_regression

In [2]:
data = pd.read_csv('exams.csv')

In [3]:
data.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group D                 high school  free/reduced   
1    male        group D            some high school      standard   
2    male        group C            some high school      standard   
3  female        group C          associate's degree  free/reduced   
4  female        group E          associate's degree      standard   

  test preparation course  math score  reading score  writing score  
0                    none          55             61             62  
1                    none          60             56             54  
2                    none          84             77             70  
3                    none          49             62             59  
4                    none         100            100            100

In [4]:
data.describe()

math score  reading score  writing score
count  1000.000000    1000.000000    1000.000000
mean     67.108000      70.065000      68.882000
std      15.057459      14.578179      15.237856
min      19.000000      27.000000      26.000000
25%      57.000000      60.000000      58.000000
50%      67.000000      70.000000      69.000000
75%      78.000000      81.000000      80.000000
max     100.000000     100.000000     100.000000

In [5]:
data.groupby(['gender']).mean()

math score  reading score  writing score
gender                                          
female      64.782         73.794         73.530
male        69.434         66.336         64.234

In [6]:
data.groupby(['race/ethnicity']).mean()

math score  reading score  writing score
race/ethnicity                                          
group A          66.506494      70.194805      68.480519
group B          62.964286      66.331633      64.693878
group C          64.583333      69.077160      67.250000
group D          68.289683      71.265873      71.857143
group E          76.238411      74.960265      73.059603

In [7]:
data.groupby(['parental level of education']).mean()

math score  reading score  writing score
parental level of education                                          
associate's degree            68.103261      72.217391      71.059783
bachelor's degree             71.327586      74.465517      75.034483
high school                   64.939560      67.428571      65.549451
master's degree               72.648649      77.283784      76.864865
some college                  67.109705      69.544304      68.641350
some high school              63.782609      66.019324      63.850242

In [8]:
data.groupby(['lunch']).mean()

math score  reading score  writing score
lunch                                                 
free/reduced   58.804598      64.195402      62.028736
standard       71.539877      73.197853      72.539877

In [9]:
data.groupby(['test preparation course']).mean()

math score  reading score  writing score
test preparation course                                          
completed                 70.621701      74.551320      75.454545
none                      65.289833      67.743551      65.481032

In [26]:
x = data['gender']
y = data['math score']

from sklearn.feature_selection import mutual_info_regression
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
le.fit(data['gender'])
list(le.classes_)

data['gender'] = le.fit_transform(data['gender']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

array([0.02725878])

In [12]:
x = data['gender']
y = data['reading score']

le = preprocessing.LabelEncoder()
le.fit(data['gender'])
list(le.classes_)

data['gender'] = le.fit_transform(data['gender']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

array([0.01100307])

In [13]:
x = data['gender']
y = data['writing score']

le = preprocessing.LabelEncoder()
le.fit(data['gender'])
list(le.classes_)

data['gender'] = le.fit_transform(data['gender']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

array([0.05376544])

In [14]:
x = data['race/ethnicity']
y = data['math score']

le = preprocessing.LabelEncoder()
le.fit(data['race/ethnicity'])
list(le.classes_)

data['race/ethnicity'] = le.fit_transform(data['race/ethnicity']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

ValueError: could not convert string to float: 'group D'

In [15]:
x = data['race/ethnicity']
y = data['reading score']

le = preprocessing.LabelEncoder()
le.fit(data['race/ethnicity'])
list(le.classes_)

data['race/ethnicity'] = le.fit_transform(data['race/ethnicity']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

array([0])

In [16]:
x = data['race/ethnicity']
y = data['writing score']

le = preprocessing.LabelEncoder()
le.fit(data['race/ethnicity'])
list(le.classes_)

data['race/ethnicity'] = le.fit_transform(data['race/ethnicity']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

array([0.0098677])

In [17]:
x = data['parental level of education']
y = data['math score']

le = preprocessing.LabelEncoder()
le.fit(data['parental level of education'])
list(le.classes_)

data['parental level of education'] = le.fit_transform(data['parental level of education']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

ValueError: could not convert string to float: 'high school'

In [18]:
x = data['parental level of education']
y = data['reading score']

le = preprocessing.LabelEncoder()
le.fit(data['parental level of education'])
list(le.classes_)

data['parental level of education'] = le.fit_transform(data['parental level of education']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

array([0])

In [19]:
x = data['parental level of education']
y = data['writing score']

le = preprocessing.LabelEncoder()
le.fit(data['parental level of education'])
list(le.classes_)

data['parental level of education'] = le.fit_transform(data['parental level of education']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

array([0.03793262])

In [20]:
x = data['lunch']
y = data['math score']

le = preprocessing.LabelEncoder()
le.fit(data['lunch'])
list(le.classes_)

data['lunch'] = le.fit_transform(data['lunch']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

ValueError: could not convert string to float: 'free/reduced'

In [21]:
x = data['lunch']
y = data['reading score']

le = preprocessing.LabelEncoder()
le.fit(data['lunch'])
list(le.classes_)

data['lunch'] = le.fit_transform(data['lunch']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

array([0.04066309])

In [22]:
x = data['lunch']
y = data['writing score']

le = preprocessing.LabelEncoder()
le.fit(data['lunch'])
list(le.classes_)

data['lunch'] = le.fit_transform(data['lunch']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

array([0.05409713])

In [23]:
x = data['test preparation course']
y = data['math score']

le = preprocessing.LabelEncoder()
le.fit(data['test preparation course'])
list(le.classes_)

data['test preparation course'] = le.fit_transform(data['test preparation course']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

ValueError: could not convert string to float: 'none'

In [24]:
x = data['test preparation course']
y = data['reading score']

le = preprocessing.LabelEncoder()
le.fit(data['test preparation course'])
list(le.classes_)

data['test preparation course'] = le.fit_transform(data['test preparation course']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

array([0.04463842])

In [25]:
x = data['test preparation course']
y = data['writing score']

le = preprocessing.LabelEncoder()
le.fit(data['test preparation course'])
list(le.classes_)

data['test preparation course'] = le.fit_transform(data['test preparation course']) 
x = x.values.reshape(-1, 1)
mutual_info_regression(x, y)

array([0.0018652])

In [ ]:
# higher MI?
# 